# ----
# Site

title: Dspread
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  bluetoothconnect:
     title: BluetoothConnect 
     position: 2
  normalapi:
    title: NormalAPIs
    position: 3
  transactionsapi:
    title: TransactionsAPIs
    position: 4
  keyinjectionapi:
    title: KeyinjectionAPIs
    position: 5
  contactus:
     title: Contactus 
     position: 6
 
    

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      comments: true

types:
  - get
  - put
  - delete
  - post
